spring.datasource.url=jdbc:postgresql://localhost:5432/takane?autoreconnect=true
spring.datasource.username=postgres
spring.datasource.password=147258
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=org.postgresql.Driver
